### PR TITLE
Search categories and books by category

### PR DESCRIPTION
**Pull request by casper1149**
I added a new endpoint to search categories
/api/v1/categories?title=<some text>

and extended the existing "books" endpoint to be able to search by category
/api/v1/books?category_id=11

### CODE REVIEW

**Comment by casper1149** [comment]
@rumyantseva Can you please take a look?

**Comment by rumyantseva** [comment]
Hi Stanislav! Thank you very much for your contribution. I like the results. I don't have any proper internet access to give a better feedback at the moment but I see a couple of things. `CategoryId` should be named as `CategoryID`, there was a guideline about it somewhere (I'll try to find it as soon as I'm online). Second thing: imports in the `middleware/categories.go` file are not formatted. Could you run `go imports` or at least `gofmt` against your changes?
These things are not critical at all but I believe that it might make sense to keep the source code as clean and as similar (in terms of naming and formatting) as possible.
Thank you again!

**Comment by casper1149** [comment]
Hi Elena, thank you for your feedback! I am new to Go, so please feel free to point out any bad practices in my code :) Sure, I'll change CategoryId -> CategoryID and fix the imports format.

A separate question, in order to compile I had to manually replace imports like 
`"github.com/rumyantseva/mif/models"` with `"../models"`, is it because I have an incorrectly set project's GOPATH? Currently it is set to the project's root. Otherwise I get compilation errors related to the improper types.

**Comment by casper1149** [comment]
Talking about "CategoryId" -> "CategoryID" you mean in the middleware/books.go, `categoryId -> categoryID` ?

**Comment by rumyantseva** [comment]
> Talking about "CategoryId" -> "CategoryID" you mean in the middleware/books.go, categoryId -> categoryID ?

@casper1149 yeah, this is what I meant :) 


> A separate question, in order to compile I had to manually replace imports like
"github.com/rumyantseva/mif/models" with "../models", is it because I have an incorrectly set project's GOPATH? Currently it is set to the project's root. Otherwise I get compilation errors related to the improper types.

Yes, it is because of the incorrect `$GOPATH`. And as I understand, you already know that relative imports are not a best practice and may cause problems and ambiguities. So, the project should be located like this: `$GOPATH/src/github.com/rumyantseva/mif`: inside of the `$GOPATH` you need to have `src` directory and store projects inside of this directory. When you use `go get`, the projects will be downloaded to `$GOPATH/src` automatically and, if there is smth to compile, as the result of `go get` the binaries will be located at `$GOPATH/pkg` and `$GOPATH/bin`.

If you have some reasons to keep different `$GOPATH` directories (e.g. for different projects or smth. like this), you can do it, just don't forget to change env variable, e.g. `GOPATH=some_new_location go get github.com/casper1149/my-super-awesome-project`.

**Comment by rumyantseva** [comment]
By the way, this project structure is not a very good example... I'm going to restructure it a little bit (e.g. to move all command line and server entry points to `cmd/`, restructure handlers etc.

**Comment by rumyantseva** [comment]
btw, If you speak Russian feel free to join our [russian-speaking Go slack](http://slack.golang-ru.com) 🤓

**Comment by casper1149** [comment]
Thank you for the GOPATH explanations and for the invite :) Shall I continue using my own build or you are going to push the new version to the registry in the nearest future?

**Comment by rumyantseva** [comment]
@casper1149 yeah, feel free to use your own build. Unfortunately, I don't have enough free time to provide all the necessary changes right now. 

I will start refactoring from the import tools (`data` directory), these changes mustn't affect the API itself.

**Comment by casper1149** [comment]
Sure, thanks!
